{{- range .Values.redirects }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-ingress-{{ .host }}
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      return {{ .statusCode }} {{ .toLocation }}$request_uri;  
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # This isn't used, but needs to be specified.
            name: example1
            port:
              number: 80
  tls:
  - hosts:
    - {{ .host | quote }}
    secretName: redirect-ingress-{{ .host }}-tls
{{- end }}
