architecture: replication
auth:
  enabled: true
  existingSecret: redis-password
  existingSecretPasswordKey: password
commonConfiguration: |
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  # Control memory usage
  maxmemory 75mb
  maxmemory-policy volatile-lru
  # Auto AOF file rewriting
  auto-aof-rewrite-percentage 100
  auto-aof-rewrite-min-size 85mb
image:
  registry: ghcr.io
  repository: wbstack/redis
  tag: 7.0.5-debian-11-r15
master:
  persistence:
    accessModes:
      - ReadWriteOnce
    enabled: true
    path: /data
    size: 1Gi
    storageClass: premium-rwo
    subPath: ""
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi
redisPort: 6379
replica:
  persistence:
    accessModes:
      - ReadWriteOnce
    enabled: true
    path: /data
    size: 1Gi
    storageClass: premium-rwo
    subPath: ""
  replicaCount: 1
  resources:
    limits:
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 250Mi
sentinel:
  enabled: false
