apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.clusterUrl }}
  project: {{ .Values.environment }}
  sources:
    - repoURL: {{ .Values.repoUrls.charts }}
      path: charts/ui
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/argocd/{{ .Values.environment }}/ui.values.yaml
    - repoURL: {{ .Values.repoUrls.deploy }}
      targetRevision: de/argo-ui-simple
      ref: values

  syncPolicy:
    automated:
      # disable self-healing for local env so we can use skaffold
      selfHeal: {{- if eq .Values.environment "local" }} false {{ else }} true {{ end}}
      prune: true
