apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: platform-apps-ingress-{{ .Values.ingressNameSuffix }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.forceSSL | quote }}
  {{- with .Values.ingressExtraAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingressHost | quote }}
    http:
      paths:
        - path: /
          backend:
            serviceName: platform-nginx
            servicePort: 8080
  {{ if .Values.tls }}
  tls:
  - hosts:
    - {{ .Values.ingressHost | quote }}
    secretName: {{ .Values.ingressNameSuffix }}-tls
  {{- end }}