certificates: []
# Example values.yaml
#
# certificates:
#   -
#     name: wikibase-cloud-tls
#     commonName: somedomain.com
#     dnsNames:
#       - '*.somedomain.com'
#     secretName: wikibase-cloud-tls
#     issuerRef: letsencrypt-prod
