apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.environment }}
spec:
  description: The {{ .Values.environment }} deployment of wikibase.cloud
  destinations:
  - name: in-cluster
    namespace: default
    server: https://kubernetes.default.svc
  sourceRepos:
  - {{ .Values.repoUrls.deploy }}
  - {{ .Values.repoUrls.charts }}